OPENAI_API_KEY= "YOUR_OPENAI_API_KEY"

LANGCHAIN_TRACING_V2="true"
LANGCHAIN_ENDPOINT="https://api.smith.langchain.com"
LANGCHAIN_API_KEY="YOUR_LANGCHAIN_API_KEY"
LANGCHAIN_PROJECT="YOUR_PROJECT_NAME"

[cookie]
expiry_days = 1
key = "demo"
name = "m2m_rolling_wave"

[credentials]
usernames = {USER_LOGIN_ID = {email = "USER_EMAIL", name = "USER_FULL_NAME", password = "USER_LOGIN_PASSWORD"}}

